### ISSUE TITLE
Native resolution

### ISSUE THREAD

**Issue by lukaslihotzki** [lukaslihotzki/pixelflood#1]
Currently, buffer size is fixed to 1280x720 and scaled to window size. Buffer should resize automatically to window size.

**Comment by jcgruenhage** [comment]
Make this optional, so that this only happens when there is no resolution specifically set via ```-b 7680x4320``` or something like that.

**Comment by lukaslihotzki** [comment]
Fixed by de53b9a. Manual, only by pressing the DEL key.
