### ISSUE TITLE
Full screen option

### ISSUE THREAD

**Issue by lukaslihotzki** [lukaslihotzki/pixelflood#2]
There should be an option to start in full screen or a key to toggle full screen.

**Comment by jcgruenhage** [comment]
When using i3, $mod + F does the trick. I don't think there would be much of an advantage in a "native" full screen mode, since most environments have similar functionality.

**Comment by lukaslihotzki** [comment]
There's at least one environment which doesn't have this functionality: Windows.
Fixed by 95f0f83.
